### ISSUE TITLE
Getting npm dependencies ERROR

### ISSUE THREAD

**Issue by shnathoskhan** [kmturley/angular2-material-firebase#4]
Dear @kmturley Pls, help me to fix this error.

@angular/cdk file cannot find a module.

**Comment by kmturley** [comment]
"CDK is the short name for Component Dev Kit. In short, the CDK is a package of components on the top of which are built most of Angular Material tools. This is the reason why the CDK lives in the Ang Material Github repo"

To solve install Angular Material using the command:
`npm install --save @angular/material @angular/cdk @angular/animations`

**Comment by shnathoskhan** [comment]
thanks for your response @kmturley ,

I got a new error, during the above-mentioned command runtime.

/angular-material-firebase>npm install --save @angular/material @angular/cdk @angular/animations
npm WARN @angular/core@4.4.7 requires a peer of zone.js@^0.8.4 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@2.0.0-beta.7-pre requires a peer of @angular/common@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@2.0.0-beta.7-pre requires a peer of @angular/compiler@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@2.0.0-beta.7-pre requires a peer of @angular/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@2.0.0-beta.7-pre requires a peer of @angular/platform-browser@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularfire2@2.0.0-beta.7-pre requires a peer of @angular/platform-browser-dynamic@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@2.0.0-beta.12 requires a peer of @angular/cdk@2.0.0-beta.12 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@6.4.6 requires a peer of @angular/core@>=6.0.0-beta.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@6.4.6 requires a peer of @angular/common@>=6.0.0-beta.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package @angular/compiler-cli is included as both a dev and production dependency.
npm WARN The package typescript is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/material@2.0.0-beta.12
+ @angular/animations@4.4.7
+ @angular/cdk@6.4.6
updated 3 packages and audited 5992 packages in 301.521s
found 19 vulnerabilities (9 low, 4 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by kmturley** [comment]
Those are mainly warnings. You should be able to run it

**Comment by shnathoskhan** [comment]
** NG Live Development Server is running on http://localhost:4200 **
Hash: 43a0978c8ea780340fcf
Time: 31985ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 159 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 46.6 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 64.4 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.73 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

WARNING in ./src/app/app.module.ts
39:16-30 "export 'MaterialModule' was not found in '@angular/material'

WARNING in ./~/@angular/material/esm5/button-toggle.es5.js
631:32-68 "export 'UNIQUE_SELECTION_DISPATCHER_PROVIDER' was not found in '@angular/cdk/collections'

WARNING in ./~/@angular/material/esm5/expansion.es5.js
607:32-68 "export 'UNIQUE_SELECTION_DISPATCHER_PROVIDER' was not found in '@angular/cdk/collections'

WARNING in ./~/@angular/material/esm5/radio.es5.js
770:32-68 "export 'UNIQUE_SELECTION_DISPATCHER_PROVIDER' was not found in '@angular/cdk/collections'

WARNING in ./~/@angular/material/esm5/select.es5.js
1430:49-74 "export 'ConnectedOverlayDirective' was not found in '@angular/cdk/overlay'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
362:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
362:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
1132:62-78 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
1132:164-170 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
1700:58-74 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
1700:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
1700:182-188 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
1700:198-204 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
1910:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
1910:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
1910:184-190 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
2440:54-70 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
2440:140-146 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/a11y.es5.js
2440:156-162 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
604:63-79 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
604:167-173 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
604:193-199 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
604:216-222 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
604:232-238 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
721:67-83 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
721:179-185 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
823:58-74 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
823:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
3386:64-80 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
3386:170-176 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
3386:193-199 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
3386:211-217 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/overlay.es5.js
3386:232-238 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/bidi.es5.js
39:11-17 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/bidi.es5.js
87:56-72 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/bidi.es5.js
87:146-152 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/platform.es5.js
79:50-66 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/platform.es5.js
79:128-134 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/collections.es5.js
462:67-83 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/observers.es5.js
38:65-81 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/observers.es5.js
164:57-73 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/observers.es5.js
164:149-155 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/scrolling.es5.js
266:58-74 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/scrolling.es5.js
266:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/scrolling.es5.js
266:168-174 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/scrolling.es5.js
517:55-71 "export 'defineInjectable' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/scrolling.es5.js
517:143-149 "export 'inject' was not found in '@angular/core'

WARNING in ./~/@angular/cdk/esm5/scrolling.es5.js
517:161-167 "export 'inject' was not found in '@angular/core'

ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol FirebaseUserConfig in E:/xampp/htdocs/angukarfirebse/p/angular-material-firebase/node_modules/angularfire2/tokens.d.ts, resolving symbol AngularFireModule.initializeApp in E:/xampp/htdocs/angukarfirebse/p/angular-material-firebase/node_modules/angularfire2/angularfire2.d.ts, resolving symbol AppModule in E:/xampp/htdocs/angukarfirebse/p/angular-material-firebase/src/app/app.module.ts, resolving symbol AppModule in E:/xampp/htdocs/angukarfirebse/p/angular-material-firebase/src/app/app.module.ts

ERROR in E:/xampp/htdocs/angukarfirebse/p/angular-material-firebase/src/app/app.module.ts (6,10): Module '"E:/xampp/htdocs/angukarfirebse/p/angular-material-firebase/node_modules/@angular/material/material"' has no exported member 'MaterialModule'. Did you mean 'MatRippleModule'?)

ERROR in E:/xampp/htdocs/angukarfirebse/p/angular-material-firebase/src/app/member/member.component.ts (37,42): Property 'filter' does not exist on type '{}'.)

ERROR in ./~/@angular/material/esm5/autocomplete.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/autocomplete.es5.js 16:0-89
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/chips.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/chips.es5.js 14:0-46
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/dialog.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/dialog.es5.js 15:0-70
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/form-field.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/form-field.es5.js 13:0-53
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/expansion.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/expansion.es5.js 19:0-43
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/datepicker.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/datepicker.es5.js 22:0-53
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/icon.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/icon.es5.js 12:0-107
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/menu.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/menu.es5.js 14:0-81
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/sidenav.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/sidenav.es5.js 21:0-81
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/select.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/select.es5.js 18:0-61
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/snack-bar.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/snack-bar.es5.js 18:0-42
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/tooltip.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/tooltip.es5.js 19:0-42
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/esm5/tabs.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in 'E:\xampp\htdocs\angukarfirebse\p\angular-material-firebase\node_modules\@angular\material\esm5'
 @ ./~/@angular/material/esm5/tabs.es5.js 23:0-57
 @ ./~/@angular/material/esm5/material.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.

**Comment by kmturley** [comment]
Ah yes, there is an issue with the versions, use this instead:
`npm install --save @angular/material@2.0.0-beta.8 @angular/cdk@2.0.0-beta.8`

I've also updated the code, so you can just download the project and start from scratch if that's easier:
https://github.com/kmturley/angular-material-firebase/commit/c6a1188a1cbf966b291fcf5ec2cf2565aa88d028
